-- Databricks notebook source
-- MAGIC %md
-- MAGIC # 🎓 Módulo 00: Introducción general a SQL
-- MAGIC ## Historia, funcionamiento, modelado de datos y estructura relacional
-- MAGIC 
-- MAGIC **Objetivo del módulo:** comprender qué es SQL, cómo interactúan los usuarios con una base de datos y cuáles son los conceptos estructurales que permiten organizar la información de forma confiable.

-- COMMAND ----------
-- MAGIC %md
-- MAGIC ## 1. Breve historia de SQL
-- MAGIC 
-- MAGIC SQL (*Structured Query Language*) nace en la década de 1970 a partir del modelo relacional propuesto por **Edgar F. Codd** en IBM.
-- MAGIC 
-- MAGIC Hitos clave:
-- MAGIC - **1970:** publicación del modelo relacional.
-- MAGIC - **1974–1979:** desarrollo de SEQUEL/SQL en IBM.
-- MAGIC - **1986:** SQL se convierte en estándar ANSI.
-- MAGIC - **1987 en adelante:** adopción ISO y evolución continua con nuevas versiones.
-- MAGIC 
-- MAGIC Desde entonces, SQL se consolidó como el lenguaje estándar para consultar, organizar y transformar datos estructurados.

-- COMMAND ----------
-- MAGIC %md
-- MAGIC ## 2. ¿Cómo funciona SQL?
-- MAGIC 
-- MAGIC SQL es un lenguaje **declarativo**: el analista indica **qué quiere obtener**, y el motor de base de datos decide **cómo ejecutar** la consulta de la forma más eficiente posible.
-- MAGIC 
-- MAGIC Flujo general:
-- MAGIC 1. El usuario escribe una consulta (`SELECT`, `WHERE`, `GROUP BY`, `JOIN`, etc.).
-- MAGIC 2. El gestor de base de datos valida sintaxis, permisos y objetos usados.
-- MAGIC 3. El optimizador genera un plan de ejecución.
-- MAGIC 4. El motor accede a tablas, índices y memoria.
-- MAGIC 5. El sistema devuelve un resultado tabular al usuario o a una aplicación.
-- MAGIC 
-- MAGIC Tipos de operaciones más comunes:
-- MAGIC - **Consulta:** `SELECT`
-- MAGIC - **Inserción:** `INSERT`
-- MAGIC - **Actualización:** `UPDATE`
-- MAGIC - **Eliminación:** `DELETE`
-- MAGIC - **Integración de datos:** `JOIN`
-- MAGIC - **Agregación:** `GROUP BY`, `HAVING`

-- COMMAND ----------
-- MAGIC %md
-- MAGIC ## 3. Comunicación entre usuario y base de datos
-- MAGIC 
-- MAGIC La interacción con una base de datos rara vez ocurre de forma aislada. Normalmente participan un usuario, una herramienta cliente, una red, el motor SQL y el almacenamiento físico.
-- MAGIC 
-- MAGIC ### Diagrama general de comunicación
-- MAGIC 
-- MAGIC ```text
-- MAGIC ┌──────────────┐
-- MAGIC │   Usuario    │
-- MAGIC └──────┬───────┘
-- MAGIC        │ escribe consultas / solicita reportes
-- MAGIC        ▼
-- MAGIC ┌──────────────┐
-- MAGIC │ Cliente SQL  │  DBeaver, Databricks, pgAdmin, aplicación web
-- MAGIC └──────┬───────┘
-- MAGIC        │ envía conexión y consulta
-- MAGIC        ▼
-- MAGIC ┌──────────────┐
-- MAGIC │ Red / Driver │  JDBC, ODBC, API
-- MAGIC └──────┬───────┘
-- MAGIC        │
-- MAGIC        ▼
-- MAGIC ┌──────────────────────┐
-- MAGIC │ Motor de Base de     │
-- MAGIC │ Datos / Optimizador  │
-- MAGIC └──────┬───────────────┘
-- MAGIC        │ lee y procesa datos
-- MAGIC        ▼
-- MAGIC ┌──────────────────────┐
-- MAGIC │ Tablas / Índices /   │
-- MAGIC │ Archivos / Memoria   │
-- MAGIC └──────────────────────┘
-- MAGIC 
-- MAGIC El resultado viaja de regreso al cliente y luego al usuario.
-- MAGIC ```
-- MAGIC 
-- MAGIC **Idea clave:** el usuario no interactúa directamente con los archivos de datos; se comunica con el motor SQL, que protege, organiza y optimiza el acceso a la información.

-- COMMAND ----------
-- MAGIC %md
-- MAGIC ## 4. Esquemas y modelos de datos
-- MAGIC 
-- MAGIC Un **modelo de datos** es la representación lógica de cómo se organizan las entidades del negocio, sus atributos y sus relaciones.
-- MAGIC 
-- MAGIC Un **esquema** es la estructura concreta donde quedan definidas tablas, columnas, tipos de dato, llaves y relaciones.
-- MAGIC 
-- MAGIC ### ¿Qué responde un buen modelo de datos?
-- MAGIC - ¿Qué entidades existen? (clientes, pedidos, productos, pagos)
-- MAGIC - ¿Qué atributos tiene cada entidad?
-- MAGIC - ¿Cómo se relacionan entre sí?
-- MAGIC - ¿Qué reglas garantizan calidad y consistencia?
-- MAGIC 
-- MAGIC ### Niveles comunes del modelado
-- MAGIC - **Modelo conceptual:** describe el negocio a alto nivel.
-- MAGIC - **Modelo lógico:** define entidades, atributos y relaciones sin depender de una tecnología específica.
-- MAGIC - **Modelo físico:** traduce el diseño a tablas reales, tipos de datos, índices y particiones.

-- COMMAND ----------
-- MAGIC %md
-- MAGIC ## 5. ¿Cómo se diseña un modelo de datos?
-- MAGIC 
-- MAGIC El diseño de un modelo de datos parte de preguntas del negocio, no de la tecnología.
-- MAGIC 
-- MAGIC Proceso recomendado:
-- MAGIC 1. **Entender el proceso de negocio:** ventas, entregas, clientes, facturación, inventario.
-- MAGIC 2. **Identificar entidades principales:** por ejemplo `clientes`, `pedidos`, `productos`.
-- MAGIC 3. **Definir atributos relevantes:** nombre, fecha, monto, estado, categoría.
-- MAGIC 4. **Establecer relaciones:** qué tabla depende de otra y en qué cardinalidad.
-- MAGIC 5. **Definir llaves:** primaria, foránea y candidatas para identificar registros.
-- MAGIC 6. **Normalizar o desnormalizar según el uso:** operación transaccional vs. analítica.
-- MAGIC 7. **Validar con casos reales de consulta:** asegurar que el diseño responde preguntas del negocio.
-- MAGIC 
-- MAGIC **Diseñar bien un modelo** mejora la calidad del dato, reduce duplicidad y facilita consultas más claras.

-- COMMAND ----------
-- MAGIC %md
-- MAGIC ## 6. Relaciones entre tablas
-- MAGIC 
-- MAGIC Las relaciones permiten conectar tablas sin repetir innecesariamente la información.
-- MAGIC 
-- MAGIC ### 6.1 Relación uno a muchos
-- MAGIC Es la relación más frecuente en bases de datos relacionales.
-- MAGIC 
-- MAGIC Ejemplo:
-- MAGIC - Un **cliente** puede tener **muchos pedidos**.
-- MAGIC - Cada **pedido** pertenece a **un solo cliente**.
-- MAGIC 
-- MAGIC ```text
-- MAGIC CLIENTES
-- MAGIC ┌───────────────┐
-- MAGIC │ id_cliente PK │◄──────────────┐
-- MAGIC │ nombre        │               │
-- MAGIC └───────────────┘               │
-- MAGIC                                 │
-- MAGIC PEDIDOS                         │
-- MAGIC ┌────────────────────┐          │
-- MAGIC │ id_pedido PK       │          │
-- MAGIC │ id_cliente FK      │──────────┘
-- MAGIC │ fecha_pedido       │
-- MAGIC │ total              │
-- MAGIC └────────────────────┘
-- MAGIC ```
-- MAGIC 
-- MAGIC ### 6.2 Muchos a uno
-- MAGIC Es la misma relación vista desde el lado contrario:
-- MAGIC - Muchos **pedidos** apuntan a un solo **cliente**.
-- MAGIC - Muchas **líneas de pedido** pueden apuntar a un solo **producto**.
-- MAGIC 
-- MAGIC **Idea clave:** una relación uno a muchos siempre puede leerse también como muchos a uno, dependiendo del punto de vista.

-- COMMAND ----------
-- MAGIC %md
-- MAGIC ## 7. Llaves principales, secundarias, foráneas e índices
-- MAGIC 
-- MAGIC ### 7.1 Llave primaria (*Primary Key*)
-- MAGIC Identifica de forma **única** cada fila de una tabla.
-- MAGIC 
-- MAGIC Ejemplo:
-- MAGIC - `id_cliente` en `clientes`
-- MAGIC - `id_pedido` en `pedidos`
-- MAGIC 
-- MAGIC Reglas habituales:
-- MAGIC - No se repite.
-- MAGIC - No debe ser nula.
-- MAGIC - Debe identificar exactamente un registro.
-- MAGIC 
-- MAGIC ### 7.2 Llave secundaria
-- MAGIC En formación introductoria suele usarse este término para referirse a un campo importante de búsqueda o a una **llave candidata/alternativa**, aunque no sea la llave primaria.
-- MAGIC 
-- MAGIC Ejemplos:
-- MAGIC - `numero_documento`
-- MAGIC - `correo_electronico`
-- MAGIC - `codigo_producto`
-- MAGIC 
-- MAGIC Estas llaves ayudan a localizar registros, pero no siempre son la llave principal elegida en el diseño final.
-- MAGIC 
-- MAGIC ### 7.3 Llave foránea (*Foreign Key*)
-- MAGIC Es una columna que guarda el identificador de otra tabla para crear la relación entre ambas.
-- MAGIC 
-- MAGIC Ejemplo:
-- MAGIC - `pedidos.id_cliente` referencia `clientes.id_cliente`
-- MAGIC 
-- MAGIC Su función es mantener la **integridad referencial**, es decir, evitar que existan pedidos asociados a clientes inexistentes.
-- MAGIC 
-- MAGIC ### 7.4 Índices
-- MAGIC Un **índice** es una estructura auxiliar que acelera la búsqueda de datos, similar al índice de un libro.
-- MAGIC 
-- MAGIC Casos típicos:
-- MAGIC - Búsquedas por identificador
-- MAGIC - Filtros frecuentes por fecha o categoría
-- MAGIC - Uniones recurrentes entre tablas
-- MAGIC 
-- MAGIC **Importante:** un índice mejora lecturas, pero también puede aumentar el costo de inserciones y actualizaciones.

-- COMMAND ----------
-- MAGIC %md
-- MAGIC ## 8. ¿Cómo se relacionan las tablas a través de las llaves?
-- MAGIC 
-- MAGIC La conexión entre tablas ocurre cuando una **llave foránea** de una tabla apunta a la **llave primaria** de otra.
-- MAGIC 
-- MAGIC ```text
-- MAGIC CLIENTES                         PEDIDOS
-- MAGIC id_cliente (PK)   ◄──────────    id_cliente (FK)
-- MAGIC nombre                          id_pedido (PK)
-- MAGIC ciudad                          fecha_pedido
-- MAGIC ```
-- MAGIC 
-- MAGIC Gracias a esta relación es posible:
-- MAGIC - saber qué pedidos pertenecen a cada cliente,
-- MAGIC - unir información con `JOIN`,
-- MAGIC - evitar duplicar el nombre del cliente en cada pedido,
-- MAGIC - conservar consistencia entre entidades.
-- MAGIC 
-- MAGIC En SQL esto habilita consultas como:
-- MAGIC - listar clientes con sus pedidos,
-- MAGIC - sumar ventas por cliente,
-- MAGIC - filtrar productos comprados por región o segmento.

-- COMMAND ----------
-- MAGIC %md
-- MAGIC ## 9. Modelos de datos para analítica: estrella y copo de nieve
-- MAGIC 
-- MAGIC En analítica y *data warehousing* es común organizar los datos para facilitar consultas, métricas y tableros.
-- MAGIC 
-- MAGIC ### 9.1 Modelo estrella
-- MAGIC Tiene una **tabla de hechos** en el centro y varias **dimensiones** alrededor.
-- MAGIC 
-- MAGIC - **Tabla de hechos:** almacena eventos medibles (ventas, viajes, órdenes).
-- MAGIC - **Dimensiones:** almacenan contexto descriptivo (cliente, producto, tiempo, región).
-- MAGIC 
-- MAGIC ```text
-- MAGIC                  DIM_TIEMPO
-- MAGIC                      │
-- MAGIC                      │
-- MAGIC DIM_CLIENTE ─── HECHO_VENTAS ─── DIM_PRODUCTO
-- MAGIC                      │
-- MAGIC                      │
-- MAGIC                  DIM_REGION
-- MAGIC ```
-- MAGIC 
-- MAGIC **Ventajas del modelo estrella:**
-- MAGIC - consultas más simples,
-- MAGIC - buen desempeño analítico,
-- MAGIC - fácil lectura para negocio y BI.
-- MAGIC 
-- MAGIC ### 9.2 Modelo copo de nieve
-- MAGIC Es una variación del modelo estrella donde algunas dimensiones se descomponen en subdimensiones más normalizadas.
-- MAGIC 
-- MAGIC ```text
-- MAGIC                          DIM_CATEGORIA
-- MAGIC                                │
-- MAGIC                                │
-- MAGIC DIM_CLIENTE ─── HECHO_VENTAS ─── DIM_PRODUCTO
-- MAGIC      │                         │
-- MAGIC      │                         │
-- MAGIC DIM_CIUDAD                DIM_MARCA
-- MAGIC      │
-- MAGIC      │
-- MAGIC DIM_PAIS
-- MAGIC ```
-- MAGIC 
-- MAGIC **Ventajas del copo de nieve:**
-- MAGIC - reduce redundancia en dimensiones,
-- MAGIC - mejora control sobre jerarquías,
-- MAGIC - puede facilitar gobierno de datos.
-- MAGIC 
-- MAGIC **Desventaja frente al estrella:** suele requerir más `JOIN`, por lo que el análisis puede volverse más complejo para el usuario.

-- COMMAND ----------
-- MAGIC %md
-- MAGIC ## 10. Principales motores y versiones SQL
-- MAGIC 
-- MAGIC Aunque SQL es estándar, cada motor agrega extensiones propias.
-- MAGIC 
-- MAGIC | Motor | Enfoque principal | Uso frecuente |
-- MAGIC |---|---|---|
-- MAGIC | **PostgreSQL** | Open source, robusto y extensible | Aplicaciones transaccionales, analítica, geodatos |
-- MAGIC | **SQL Server** | Ecosistema Microsoft empresarial | BI corporativo, sistemas de negocio, data warehouse |
-- MAGIC | **Spark SQL** | SQL distribuido sobre Apache Spark | Big Data, ETL masivo, Lakehouse |
-- MAGIC | **MySQL** | Popular y sencillo de operar | Aplicaciones web, backend de productos |
-- MAGIC | **Oracle Database** | Alto rendimiento y capacidades enterprise | Finanzas, telecom, sistemas críticos |
-- MAGIC | **SQLite** | Ligero y embebido | Apps móviles, prototipos, software local |
-- MAGIC | **BigQuery / Snowflake** | SQL en la nube y analítica escalable | Analítica moderna, ciencia de datos, BI cloud |

-- COMMAND ----------
-- MAGIC %md
-- MAGIC ## 11. SQL en este curso (Databricks SQL / Spark SQL)
-- MAGIC 
-- MAGIC En este curso trabajarás en Databricks, donde SQL se ejecuta sobre el motor de Spark SQL.
-- MAGIC 
-- MAGIC Beneficios para analítica:
-- MAGIC - Procesamiento distribuido para grandes volúmenes.
-- MAGIC - Integración con notebooks y flujos de ciencia de datos.
-- MAGIC - Compatibilidad con patrones SQL ampliamente conocidos.
-- MAGIC - Facilidad para trabajar con tablas de ejemplo y entornos formativos.

-- COMMAND ----------
-- MAGIC %md
-- MAGIC ## 12. Cierre del módulo
-- MAGIC 
-- MAGIC En este módulo conociste:
-- MAGIC - El origen histórico de SQL.
-- MAGIC - Cómo se comunica un usuario con una base de datos.
-- MAGIC - Qué es un modelo de datos y cómo se diseña.
-- MAGIC - Relaciones uno a muchos y muchos a uno.
-- MAGIC - Llaves primarias, secundarias y foráneas.
-- MAGIC - El papel de los índices.
-- MAGIC - Las diferencias entre modelos estrella y copo de nieve.
-- MAGIC 
-- MAGIC En el siguiente notebook comenzarás la práctica aplicada en Databricks con catálogos, esquemas, tablas y consultas básicas.
